import { Component } from '@angular/core';
import { DashboardNotification } from '../../../dashboard/dashboard-notification/dashboard-notification';
import {
  NotificationItem,
  NotificationType,
} from '../../../../models/NotificationItem';

@Component({
  selector: 'app-organizer-dashboard-notification',
  imports: [DashboardNotification],
  templateUrl: './organizer-dashboard-notification.html',
  styleUrl: './organizer-dashboard-notification.scss',
})
export class OrganizerDashboardNotification {
  tabs: Array<'全部' | '未讀' | NotificationType> = [
    '全部',
    '未讀',
    '報名相關',
    '付款相關',
    '活動異動',
    '系統公告',
  ];

  notifications: NotificationItem[] = [
    {
      icon: 'bi bi-calendar-event',
      iconClass: 'orange',
      title: '品牌「森日甜點」送出報名申請：夏日綠意市集',
      status: '新報名',
      statusClass: 'pending',
      date: '2026/06/02 14:30',
      unread: true,
      type: '報名相關',
    },
    {
      icon: 'bi bi-wallet2',
      iconClass: 'blue',
      title: '品牌「木木手作」已完成付款：貓貓森林市集',
      status: '付款完成',
      statusClass: 'payment',
      date: '2026/06/02 13:10',
      unread: true,
      type: '付款相關',
    },
    {
      icon: 'bi bi-arrow-repeat',
      iconClass: 'green',
      title: '品牌「草語選物」申請退款：夏日綠意市集',
      status: '退款申請',
      statusClass: 'refund',
      date: '2026/06/02 11:45',
      unread: true,
      type: '付款相關',
    },
    {
      icon: 'bi bi-pencil',
      iconClass: 'purple',
      title: '品牌「日常手作所」已完成補件並重新送審：秋日手作市集',
      status: '補件完成',
      statusClass: 'success',
      date: '2026/06/02 10:15',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-map',
      iconClass: 'teal',
      title: '品牌「木木手作」已完成攤位選擇：貓貓森林市集',
      status: '完成選位',
      statusClass: 'success',
      date: '2026/06/01 16:20',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-megaphone',
      iconClass: 'yellow',
      title: '夏日綠意市集活動時間調整，請參考最新公告',
      status: '活動異動',
      statusClass: 'info',
      date: '2026/05/29 09:30',
      unread: false,
      type: '活動異動',
    },
    {
      icon: 'bi bi-calendar-x',
      iconClass: 'red',
      title: '冬季暖心市集已下架或取消',
      status: '已下架',
      statusClass: 'cancel',
      date: '2026/05/30 15:05',
      unread: false,
      type: '活動異動',
    },
    {
      icon: 'bi bi-check-circle',
      iconClass: 'blue',
      title: '春日野餐市集活動已結束，感謝您的參與',
      status: '活動結束',
      statusClass: 'success',
      date: '2026/05/26 18:30',
      unread: false,
      type: '系統公告',
    },
    {
      icon: 'bi bi-calendar-event',
      iconClass: 'orange',
      title: '品牌「小島布作」送出報名申請：秋日手作市集',
      status: '新報名',
      statusClass: 'pending',
      date: '2026/05/25 14:05',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-wallet2',
      iconClass: 'blue',
      title: '品牌「暖木咖啡」已完成付款：夏日綠意市集',
      status: '付款完成',
      statusClass: 'payment',
      date: '2026/05/24 12:40',
      unread: false,
      type: '付款相關',
    },
    {
      icon: 'bi bi-x-circle',
      iconClass: 'red',
      title: '品牌「花日選物」取消報名：貓貓森林市集',
      status: '已取消',
      statusClass: 'cancel',
      date: '2026/05/23 17:20',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-pencil-square',
      iconClass: 'purple',
      title: '品牌「午後甜點」已更新報名資料：春日野餐市集',
      status: '資料更新',
      statusClass: 'info',
      date: '2026/05/22 09:50',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-arrow-repeat',
      iconClass: 'green',
      title: '品牌「果嶼生活」退款審核已完成：秋日手作市集',
      status: '退款完成',
      statusClass: 'success',
      date: '2026/05/21 16:10',
      unread: false,
      type: '付款相關',
    },
    {
      icon: 'bi bi-megaphone',
      iconClass: 'yellow',
      title: '系統公告：主辦方後台將於今晚 23:00 進行維護',
      status: '系統公告',
      statusClass: 'info',
      date: '2026/05/20 18:00',
      unread: false,
      type: '系統公告',
    },
    {
      icon: 'bi bi-calendar-event',
      iconClass: 'orange',
      title: '品牌「森森植栽」送出報名申請：冬季暖心市集',
      status: '新報名',
      statusClass: 'pending',
      date: '2026/05/19 11:35',
      unread: false,
      type: '報名相關',
    },
    {
      icon: 'bi bi-check-circle',
      iconClass: 'blue',
      title: '市集「春日野餐市集」已完成活動資料歸檔',
      status: '資料歸檔',
      statusClass: 'success',
      date: '2026/05/18 15:20',
      unread: false,
      type: '系統公告',
    },
  ];
}