import { Component } from '@angular/core';
import { DashboardNotification } from '../../dashboard/dashboard-notification/dashboard-notification';
import type { NotificationItem, NotificationType } from '../../../models/NotificationItem';

@Component({
  selector: 'app-admin-dashboard-notification',
  imports: [DashboardNotification],
  templateUrl: './admin-dashboard-notification.html',
  styleUrl: './admin-dashboard-notification.scss',
})
export class AdminDashboardNotification {

  tabs: Array<'全部' | '未讀' | NotificationType> = [
    '全部',
    '未讀',
    '主辦方',
    '活動',
    '系統',
    '異常',
  ];

  notifications: NotificationItem[] = [
    {
      icon: 'bi bi-person-plus',
      iconClass: 'orange',
      title: '新主辦方「森林生活市集」申請加入平台，請進行審核',
      status: '新申請',
      statusClass: 'pending',
      date: '2026/06/02 14:30',
      unread: true,
      type: '主辦方',
    },
    {
      icon: 'bi bi-file-earmark-check',
      iconClass: 'green',
      title: '主辦方「日日好市」已重新送出資料，請確認補件內容',
      status: '補件完成',
      statusClass: 'success',
      date: '2026/06/02 13:10',
      unread: true,
      type: '主辦方',
    },
    {
      icon: 'bi bi-calendar-plus',
      iconClass: 'blue',
      title: '主辦方「森手作坊」建立新活動：夏日綠意市集，請確認活動內容',
      status: '新活動',
      statusClass: 'info',
      date: '2026/06/02 11:45',
      unread: true,
      type: '活動',
    },
    {
      icon: 'bi bi-exclamation-triangle',
      iconClass: 'red',
      title: '主辦方帳號「user_****@gmail.com」登入異次數過高，請協助確認',
      status: '異常提醒',
      statusClass: 'cancel',
      date: '2026/06/02 10:15',
      unread: true,
      type: '異常',
    },
    {
      icon: 'bi bi-megaphone',
      iconClass: 'yellow',
      title: '系統將於 06/10 (二) 00:00 - 02:00 進行維護，期間將暫停部分服務',
      status: '系統公告',
      statusClass: 'info',
      date: '2026/06/01 18:20',
      unread: false,
      type: '系統',
    },
    {
      icon: 'bi bi-person-plus',
      iconClass: 'orange',
      title: '新主辦方「手作小日子」申請加入平台，請進行審核',
      status: '新申請',
      statusClass: 'pending',
      date: '2026/06/01 15:05',
      unread: false,
      type: '主辦方',
    },
    {
      icon: 'bi bi-flag',
      iconClass: 'green',
      title: '主辦方「春語植物市集」活動已結束，相關報告資料已歸檔',
      status: '活動結束',
      statusClass: 'success',
      date: '2026/05/30 09:30',
      unread: false,
      type: '活動',
    },
    {
      icon: 'bi bi-shield-check',
      iconClass: 'blue',
      title: '已協助主辦方「木木手作」重設密碼，請確認後續帳號狀態',
      status: '安全提醒',
      statusClass: 'info',
      date: '2026/05/29 08:40',
      unread: false,
      type: '系統',
    },
    {
      icon: 'bi bi-calendar-x',
      iconClass: 'red',
      title: '活動「冬季暖心市集」被檢舉違規內容，請進行審查',
      status: '待審查',
      statusClass: 'cancel',
      date: '2026/05/28 14:00',
      unread: false,
      type: '異常',
    },
    {
      icon: 'bi bi-person-check',
      iconClass: 'green',
      title: '主辦方「草語選物」已完成身份驗證，帳號已啟用',
      status: '審核通過',
      statusClass: 'success',
      date: '2026/05/27 10:20',
      unread: false,
      type: '主辦方',
    },
    {
      icon: 'bi bi-gear',
      iconClass: 'teal',
      title: '平台版本已更新至 v2.3.1，新增主辦方批次審核功能',
      status: '系統更新',
      statusClass: 'info',
      date: '2026/05/26 09:00',
      unread: false,
      type: '系統',
    },
    {
      icon: 'bi bi-calendar-event',
      iconClass: 'blue',
      title: '主辦方「木木手作」發布新市集活動：秋日手作展',
      status: '已上架',
      statusClass: 'success',
      date: '2026/05/25 16:30',
      unread: false,
      type: '活動',
    },
  ];
}
